/**
 * `npm run gen:assets` (RFR-11, AD-9): scans Client/assets/ and writes the typed
 * manifest src/generated/assets.gen.ts. Deterministic (sorted, no timestamps) so
 * gen:check can diff it in CI. Code refers to assets only through these keys;
 * a misspelled key is a compile error.
 *
 * Kinds:
 *  - image:    *.png / *.jpg that have no sibling .json
 *  - aseprite: *.png with a sibling Aseprite-format *.json (frame tags = animations)
 *  - audio:    *.wav / *.mp3 / *.ogg
 *  - font:     *.woff2 / *.ttf
 */
import { readdirSync, statSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, relative, extname, dirname } from 'node:path';

const ROOT = 'assets';
const OUT = 'src/generated/assets.gen.ts';

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const p = join(dir, name);
      return statSync(p).isDirectory() ? walk(p) : [p];
    });
}

const files = walk(ROOT).map((f) => relative(ROOT, f).split('\\').join('/'));
const fileSet = new Set(files);
const keyOf = (path: string) => path.slice(0, path.length - extname(path).length);

const image: Record<string, string> = {};
const aseprite: Record<string, { png: string; json: string }> = {};
const audio: Record<string, string> = {};
const font: Record<string, string> = {};

for (const f of files) {
  const ext = extname(f).toLowerCase();
  const key = keyOf(f);
  if (ext === '.png' || ext === '.jpg') {
    if (ext === '.png' && fileSet.has(`${key}.json`)) aseprite[key] = { png: f, json: `${key}.json` };
    else image[key] = f;
  } else if (ext === '.wav' || ext === '.mp3' || ext === '.ogg') {
    audio[key] = f;
  } else if (ext === '.woff2' || ext === '.ttf') {
    font[key] = f;
  }
}

const block = (obj: object) => JSON.stringify(obj, Object.keys(obj).sort(), 2);
const sortedObj = <T>(o: Record<string, T>) =>
  Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k] as T]));

const body = `// GENERATED by tools/gen-assets.ts — do not edit. Run \`npm run gen:assets\`.
/* eslint-disable */

export const Assets = {
  image: ${JSON.stringify(sortedObj(image), null, 2).replace(/\n/g, '\n  ')},
  aseprite: ${JSON.stringify(sortedObj(aseprite), null, 2).replace(/\n/g, '\n  ')},
  audio: ${JSON.stringify(sortedObj(audio), null, 2).replace(/\n/g, '\n  ')},
  font: ${JSON.stringify(sortedObj(font), null, 2).replace(/\n/g, '\n  ')},
} as const;

export type ImageKey = keyof typeof Assets.image;
export type AsepriteKey = keyof typeof Assets.aseprite;
export type AudioKey = keyof typeof Assets.audio;
export type FontKey = keyof typeof Assets.font;
export type AssetKey = ImageKey | AsepriteKey | AudioKey;

export const ALL_ASSET_KEYS: readonly string[] = ${block([
  ...Object.keys(image),
  ...Object.keys(aseprite),
  ...Object.keys(audio),
  ...Object.keys(font),
].sort())};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body.replace(/\r\n/g, '\n'));
console.log(
  `gen:assets: ${Object.keys(image).length} images, ${Object.keys(aseprite).length} aseprite sheets, ` +
    `${Object.keys(audio).length} audio, ${Object.keys(font).length} fonts → ${OUT}`,
);
