// <auto-generated />
using System;
using System.Collections.Generic;
using InfinityGrove.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfinityGrove.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InfinityGroveDbContext))]
    [Migration("20260906232615_AddPlayerProgressAndEvents")]
    partial class AddPlayerProgressAndEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("SteamId64")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("steam_id64");

                    b.HasKey("Id");

                    b.HasIndex("SteamId64")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Events.PlayerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rejection_reason");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "SequenceNumber");

                    b.ToTable("player_events", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.PlayerProgress", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("FurthestStageCleared")
                        .HasColumnType("integer")
                        .HasColumnName("furthest_stage_cleared");

                    b.Property<int>("GoldExponent")
                        .HasColumnType("integer")
                        .HasColumnName("gold_exponent");

                    b.Property<double>("GoldMantissa")
                        .HasColumnType("double precision")
                        .HasColumnName("gold_mantissa");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_applied_sequence");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<Guid>>("_activeSquadHeroIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("active_squad_hero_ids");

                    b.HasKey("AccountId");

                    b.ToTable("player_progress", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.RosterEntry", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("HeroDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_definition_id");

                    b.Property<int>("OwnedCount")
                        .HasColumnType("integer")
                        .HasColumnName("owned_count");

                    b.HasKey("AccountId", "HeroDefinitionId");

                    b.ToTable("roster_entries", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.RosterEntry", b =>
                {
                    b.HasOne("InfinityGrove.Backend.Domain.Progress.PlayerProgress", null)
                        .WithMany("Roster")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.PlayerProgress", b =>
                {
                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
