// <auto-generated />
using System;
using System.Collections.Generic;
using InfinityGrove.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfinityGrove.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InfinityGroveDbContext))]
    [Migration("20260907001045_AddMarketPriceCacheAndAbuseFlags")]
    partial class AddMarketPriceCacheAndAbuseFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("SteamId64")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("steam_id64");

                    b.HasKey("Id");

                    b.HasIndex("SteamId64")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Cards.CardInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HeroDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_definition_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "HeroDefinitionId", "State");

                    b.ToTable("card_instances", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Cards.SteamInventoryOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long?>("SteamItemDefId")
                        .HasColumnType("bigint")
                        .HasColumnName("steam_item_def_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<Guid>>("_cardInstanceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("card_instance_ids");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("steam_inventory_outbox", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Events.PlayerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rejection_reason");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("AccountId", "SequenceNumber");

                    b.ToTable("player_events", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Market.MarketPriceSnapshot", b =>
                {
                    b.Property<Guid>("HeroDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_definition_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("LowestPriceDisplay")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lowest_price_display");

                    b.Property<string>("MedianPriceDisplay")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("median_price_display");

                    b.Property<string>("Volume")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("volume");

                    b.HasKey("HeroDefinitionId");

                    b.ToTable("market_price_snapshots", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.MarketAbuse.MarketAbuseFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<int>("ObservedEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("observed_event_count");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal_type");

                    b.Property<int>("ThresholdEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_event_count");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "SignalType", "DetectedAtUtc");

                    b.ToTable("market_abuse_flags", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.PlayerProgress", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("FurthestStageCleared")
                        .HasColumnType("integer")
                        .HasColumnName("furthest_stage_cleared");

                    b.Property<int>("GoldExponent")
                        .HasColumnType("integer")
                        .HasColumnName("gold_exponent");

                    b.Property<double>("GoldMantissa")
                        .HasColumnType("double precision")
                        .HasColumnName("gold_mantissa");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_applied_sequence");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<List<Guid>>("_activeSquadHeroIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("active_squad_hero_ids");

                    b.HasKey("AccountId");

                    b.ToTable("player_progress", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.RosterEntry", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("HeroDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_definition_id");

                    b.Property<int>("OwnedCount")
                        .HasColumnType("integer")
                        .HasColumnName("owned_count");

                    b.Property<int>("StarTier")
                        .HasColumnType("integer")
                        .HasColumnName("star_tier");

                    b.HasKey("AccountId", "HeroDefinitionId");

                    b.ToTable("roster_entries", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Purchases.SummoningStonePurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("GrantedCardInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_card_instance_id");

                    b.Property<Guid>("HeroDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_definition_id");

                    b.Property<Guid?>("OutboxEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_entry_id");

                    b.Property<long>("PriceAmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("price_amount_minor_units");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("SteamOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("steam_order_id");

                    b.Property<string>("SteamTransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("steam_transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SteamOrderId")
                        .IsUnique();

                    b.ToTable("summoning_stone_purchases", (string)null);
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.RosterEntry", b =>
                {
                    b.HasOne("InfinityGrove.Backend.Domain.Progress.PlayerProgress", null)
                        .WithMany("Roster")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityGrove.Backend.Domain.Progress.PlayerProgress", b =>
                {
                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
